@base_url = http://localhost:3000

### App request
GET http://localhost:3000/


### Auth request
GET http://localhost:3000/auth/hello/1


### User request
POST http://localhost:3000/users
Content-Type: application/json

{
    "id": 1,
  "username": "TRRRRRR Doe",
  "password": "mdp"
}